[project]
name = "mcp-warmup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "VISHAL0713", email = "vgv0907@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=4.0.2",
]

[project.scripts]
mcp-warmup = "mcp_warmup:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
